"""
This type stub file was generated by pyright.
"""

"""Storage API IAM policy definitions

For allowed roles / permissions, see:
https://cloud.google.com/storage/docs/access-control/iam
"""
STORAGE_OBJECT_CREATOR_ROLE = "roles/storage.objectCreator"
STORAGE_OBJECT_VIEWER_ROLE = "roles/storage.objectViewer"
STORAGE_OBJECT_ADMIN_ROLE = "roles/storage.objectAdmin"
STORAGE_ADMIN_ROLE = "roles/storage.admin"
STORAGE_VIEWER_ROLE = "Viewer"
STORAGE_EDITOR_ROLE = "Editor"
STORAGE_OWNER_ROLE = "Owners"
STORAGE_BUCKETS_CREATE = "storage.buckets.create"
STORAGE_BUCKETS_DELETE = "storage.buckets.delete"
STORAGE_BUCKETS_GET = "storage.buckets.get"
STORAGE_BUCKETS_GET_IAM_POLICY = "storage.buckets.getIamPolicy"
STORAGE_BUCKETS_LIST = "storage.buckets.list"
STORAGE_BUCKETS_SET_IAM_POLICY = "storage.buckets.setIamPolicy"
STORAGE_BUCKETS_UPDATE = "storage.buckets.list"
STORAGE_OBJECTS_CREATE = "storage.objects.create"
STORAGE_OBJECTS_DELETE = "storage.objects.delete"
STORAGE_OBJECTS_GET = "storage.objects.get"
STORAGE_OBJECTS_GET_IAM_POLICY = "storage.objects.getIamPolicy"
STORAGE_OBJECTS_LIST = "storage.objects.list"
STORAGE_OBJECTS_SET_IAM_POLICY = "storage.objects.setIamPolicy"
STORAGE_OBJECTS_UPDATE = "storage.objects.update"
