"""
This type stub file was generated by pyright.
"""

import requests
from google.api_core import exceptions, retry

_RETRYABLE_TYPES = (exceptions.TooManyRequests, exceptions.InternalServerError, exceptions.BadGateway, exceptions.ServiceUnavailable, exceptions.GatewayTimeout, requests.ConnectionError)
_ADDITIONAL_RETRYABLE_STATUS_CODES = (408, )
DEFAULT_RETRY = retry.Retry(predicate=_should_retry)
class ConditionalRetryPolicy(object):
    """A class for use when an API call is only conditionally safe to retry.

    This class is intended for use in inspecting the API call parameters of an
    API call to verify that any flags necessary to make the API call idempotent
    (such as specifying an ``if_generation_match`` or related flag) are present.

    It can be used in place of a ``retry.Retry`` object, in which case
    ``_http.Connection.api_request`` will pass the requested api call keyword
    arguments into the ``conditional_predicate`` and return the ``retry_policy``
    if the conditions are met.

    :type retry_policy: class:`google.api_core.retry.Retry`
    :param retry_policy: A retry object defining timeouts, persistence and which
        exceptions to retry.

    :type conditional_predicate: callable
    :param conditional_predicate: A callable that accepts exactly the number of
        arguments in ``required_kwargs``, in order, and returns True if the
        arguments have sufficient data to determine that the call is safe to
        retry (idempotent).

    :type required_kwargs: list(str)
    :param required_kwargs:
        A list of keyword argument keys that will be extracted from the API call
        and passed into the ``conditional predicate`` in order.
    """
    def __init__(self, retry_policy, conditional_predicate, required_kwargs) -> None:
        ...
    
    def get_retry_policy_if_conditions_met(self, **kwargs):
        ...
    


def is_generation_specified(query_params):
    """Return True if generation or if_generation_match is specified."""
    ...

def is_metageneration_specified(query_params):
    """Return True if if_metageneration_match is specified."""
    ...

def is_etag_in_json(data):
    """Return True if an etag is contained in the JSON body.

    Indended for use on calls with relatively short JSON payloads."""
    ...

DEFAULT_RETRY_IF_GENERATION_SPECIFIED = ConditionalRetryPolicy(DEFAULT_RETRY, is_generation_specified, ["query_params"])
DEFAULT_RETRY_IF_METAGENERATION_SPECIFIED = ConditionalRetryPolicy(DEFAULT_RETRY, is_metageneration_specified, ["query_params"])
DEFAULT_RETRY_IF_ETAG_IN_JSON = ConditionalRetryPolicy(DEFAULT_RETRY, is_etag_in_json, ["data"])
