"""
This type stub file was generated by pyright.
"""

import six

"""
This type stub file was generated by pyright.
"""
_HTTP_CODE_TO_EXCEPTION = {  }
_GRPC_CODE_TO_EXCEPTION = {  }
_INT_TO_GRPC_CODE = {  }
if grpc is not None:
    ...
class GoogleAPIError(Exception):
    """Base class for all exceptions raised by Google API Clients."""
    ...


class DuplicateCredentialArgs(GoogleAPIError):
    """Raised when multiple credentials are passed."""
    ...


@six.python_2_unicode_compatible
class RetryError(GoogleAPIError):
    """Raised when a function has exhausted all of its available retries.

    Args:
        message (str): The exception message.
        cause (Exception): The last exception raised when retring the
            function.
    """
    def __init__(self, message, cause) -> None:
        ...
    
    @property
    def cause(self):
        """The last exception raised when retrying the function."""
        ...
    
    def __str__(self) -> str:
        ...
    


class _GoogleAPICallErrorMeta(type):
    """Metaclass for registering GoogleAPICallError subclasses."""
    def __new__(mcs, name, bases, class_dict):
        ...
    


@six.python_2_unicode_compatible
@six.add_metaclass(_GoogleAPICallErrorMeta)
class GoogleAPICallError(GoogleAPIError):
    """Base class for exceptions raised by calling API methods.

    Args:
        message (str): The exception message.
        errors (Sequence[Any]): An optional list of error details.
        response (Union[requests.Request, grpc.Call]): The response or
            gRPC call metadata.
    """
    code = ...
    grpc_status_code = ...
    def __init__(self, message, errors=..., response=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def errors(self):
        """Detailed error information.

        Returns:
            Sequence[Any]: A list of additional error details.
        """
        ...
    
    @property
    def response(self):
        """Optional[Union[requests.Request, grpc.Call]]: The response or
        gRPC call metadata."""
        ...
    


class Redirection(GoogleAPICallError):
    """Base class for for all redirection (HTTP 3xx) responses."""
    ...


class MovedPermanently(Redirection):
    """Exception mapping a ``301 Moved Permanently`` response."""
    code = ...


class NotModified(Redirection):
    """Exception mapping a ``304 Not Modified`` response."""
    code = ...


class TemporaryRedirect(Redirection):
    """Exception mapping a ``307 Temporary Redirect`` response."""
    code = ...


class ResumeIncomplete(Redirection):
    """Exception mapping a ``308 Resume Incomplete`` response.

    .. note:: :attr:`http_client.PERMANENT_REDIRECT` is ``308``, but Google
        APIs differ in their use of this status code.
    """
    code = ...


class ClientError(GoogleAPICallError):
    """Base class for all client error (HTTP 4xx) responses."""
    ...


class BadRequest(ClientError):
    """Exception mapping a ``400 Bad Request`` response."""
    code = ...


class InvalidArgument(BadRequest):
    """Exception mapping a :attr:`grpc.StatusCode.INVALID_ARGUMENT` error."""
    grpc_status_code = ...


class FailedPrecondition(BadRequest):
    """Exception mapping a :attr:`grpc.StatusCode.FAILED_PRECONDITION`
    error."""
    grpc_status_code = ...


class OutOfRange(BadRequest):
    """Exception mapping a :attr:`grpc.StatusCode.OUT_OF_RANGE` error."""
    grpc_status_code = ...


class Unauthorized(ClientError):
    """Exception mapping a ``401 Unauthorized`` response."""
    code = ...


class Unauthenticated(Unauthorized):
    """Exception mapping a :attr:`grpc.StatusCode.UNAUTHENTICATED` error."""
    grpc_status_code = ...


class Forbidden(ClientError):
    """Exception mapping a ``403 Forbidden`` response."""
    code = ...


class PermissionDenied(Forbidden):
    """Exception mapping a :attr:`grpc.StatusCode.PERMISSION_DENIED` error."""
    grpc_status_code = ...


class NotFound(ClientError):
    """Exception mapping a ``404 Not Found`` response or a
    :attr:`grpc.StatusCode.NOT_FOUND` error."""
    code = ...
    grpc_status_code = ...


class MethodNotAllowed(ClientError):
    """Exception mapping a ``405 Method Not Allowed`` response."""
    code = ...


class Conflict(ClientError):
    """Exception mapping a ``409 Conflict`` response."""
    code = ...


class AlreadyExists(Conflict):
    """Exception mapping a :attr:`grpc.StatusCode.ALREADY_EXISTS` error."""
    grpc_status_code = ...


class Aborted(Conflict):
    """Exception mapping a :attr:`grpc.StatusCode.ABORTED` error."""
    grpc_status_code = ...


class LengthRequired(ClientError):
    """Exception mapping a ``411 Length Required`` response."""
    code = ...


class PreconditionFailed(ClientError):
    """Exception mapping a ``412 Precondition Failed`` response."""
    code = ...


class RequestRangeNotSatisfiable(ClientError):
    """Exception mapping a ``416 Request Range Not Satisfiable`` response."""
    code = ...


class TooManyRequests(ClientError):
    """Exception mapping a ``429 Too Many Requests`` response."""
    code = ...


class ResourceExhausted(TooManyRequests):
    """Exception mapping a :attr:`grpc.StatusCode.RESOURCE_EXHAUSTED` error."""
    grpc_status_code = ...


class Cancelled(ClientError):
    """Exception mapping a :attr:`grpc.StatusCode.CANCELLED` error."""
    code = ...
    grpc_status_code = ...


class ServerError(GoogleAPICallError):
    """Base for 5xx responses."""
    ...


class InternalServerError(ServerError):
    """Exception mapping a ``500 Internal Server Error`` response. or a
    :attr:`grpc.StatusCode.INTERNAL` error."""
    code = ...
    grpc_status_code = ...


class Unknown(ServerError):
    """Exception mapping a :attr:`grpc.StatusCode.UNKNOWN` error."""
    grpc_status_code = ...


class DataLoss(ServerError):
    """Exception mapping a :attr:`grpc.StatusCode.DATA_LOSS` error."""
    grpc_status_code = ...


class MethodNotImplemented(ServerError):
    """Exception mapping a ``501 Not Implemented`` response or a
    :attr:`grpc.StatusCode.UNIMPLEMENTED` error."""
    code = ...
    grpc_status_code = ...


class BadGateway(ServerError):
    """Exception mapping a ``502 Bad Gateway`` response."""
    code = ...


class ServiceUnavailable(ServerError):
    """Exception mapping a ``503 Service Unavailable`` response or a
    :attr:`grpc.StatusCode.UNAVAILABLE` error."""
    code = ...
    grpc_status_code = ...


class GatewayTimeout(ServerError):
    """Exception mapping a ``504 Gateway Timeout`` response."""
    code = ...


class DeadlineExceeded(GatewayTimeout):
    """Exception mapping a :attr:`grpc.StatusCode.DEADLINE_EXCEEDED` error."""
    grpc_status_code = ...


def exception_class_for_http_status(status_code):
    """Return the exception class for a specific HTTP status code.

    Args:
        status_code (int): The HTTP status code.

    Returns:
        :func:`type`: the appropriate subclass of :class:`GoogleAPICallError`.
    """
    ...

def from_http_status(status_code, message, **kwargs):
    """Create a :class:`GoogleAPICallError` from an HTTP status code.

    Args:
        status_code (int): The HTTP status code.
        message (str): The exception message.
        kwargs: Additional arguments passed to the :class:`GoogleAPICallError`
            constructor.

    Returns:
        GoogleAPICallError: An instance of the appropriate subclass of
            :class:`GoogleAPICallError`.
    """
    ...

def from_http_response(response):
    """Create a :class:`GoogleAPICallError` from a :class:`requests.Response`.

    Args:
        response (requests.Response): The HTTP response.

    Returns:
        GoogleAPICallError: An instance of the appropriate subclass of
            :class:`GoogleAPICallError`, with the message and errors populated
            from the response.
    """
    ...

def exception_class_for_grpc_status(status_code):
    """Return the exception class for a specific :class:`grpc.StatusCode`.

    Args:
        status_code (grpc.StatusCode): The gRPC status code.

    Returns:
        :func:`type`: the appropriate subclass of :class:`GoogleAPICallError`.
    """
    ...

def from_grpc_status(status_code, message, **kwargs):
    """Create a :class:`GoogleAPICallError` from a :class:`grpc.StatusCode`.

    Args:
        status_code (Union[grpc.StatusCode, int]): The gRPC status code.
        message (str): The exception message.
        kwargs: Additional arguments passed to the :class:`GoogleAPICallError`
            constructor.

    Returns:
        GoogleAPICallError: An instance of the appropriate subclass of
            :class:`GoogleAPICallError`.
    """
    ...

def from_grpc_error(rpc_exc):
    """Create a :class:`GoogleAPICallError` from a :class:`grpc.RpcError`.

    Args:
        rpc_exc (grpc.RpcError): The gRPC error.

    Returns:
        GoogleAPICallError: An instance of the appropriate subclass of
            :class:`GoogleAPICallError`.
    """
    ...

