"""
This type stub file was generated by pyright.
"""

from .. import *

def runTests():
    ...

def testAliases():
    ...

def testAColor(errors, name, code, isBackground):
    ...

def testColors(colors, startCode, *, isBackground=...):
    ...

