"""
This type stub file was generated by pyright.
"""

from .. import *

miscStyles = [("bold", 1), ("dim", 2), ("underline", 3), ("hidden", 6)]
def runTests():
    ...

def toResults(errors, style):
    ...

