"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function
from fire.core import Fire

"""The Python Fire module."""
__version__ = '0.3.1'
