"""
This type stub file was generated by pyright.
"""

"""Enables use of Python Fire as a "main" function (i.e. `python -m fire`).

This allows using Fire with third-party libraries without modifying their code.
"""
def main(args):
  ...

if __name__ == '__main__':
  ...
