"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the completion module."""
class TabCompletionTest(testutils.BaseTestCase):
  def testCompletionBashScript(self):
    ...
  
  def testCompletionFishScript(self):
    ...
  
  def testFnCompletions(self):
    ...
  
  def testListCompletions(self):
    ...
  
  def testDictCompletions(self):
    ...
  
  def testDictCompletionsVerbose(self):
    ...
  
  def testDeepDictCompletions(self):
    ...
  
  def testDeepDictScript(self):
    ...
  
  def testFnScript(self):
    ...
  
  def testClassScript(self):
    ...
  
  def testDeepDictFishScript(self):
    ...
  
  def testFnFishScript(self):
    ...
  
  def testClassFishScript(self):
    ...
  
  def testNonStringDictCompletions(self):
    ...
  
  def testGeneratorCompletions(self):
    ...
  
  def testClassCompletions(self):
    ...
  
  def testObjectCompletions(self):
    ...
  
  def testMethodCompletions(self):
    ...
  


if __name__ == '__main__':
  ...
