"""
This type stub file was generated by pyright.
"""

import mock
import six
from fire import testutils

"""Tests for the core module."""
class CoreTest(testutils.BaseTestCase):
  def testOneLineResult(self):
    ...
  
  def testOneLineResultCircularRef(self):
    ...
  
  @mock.patch('fire.interact.Embed')
  def testInteractiveMode(self, mock_embed):
    ...
  
  @mock.patch('fire.interact.Embed')
  def testInteractiveModeFullArgument(self, mock_embed):
    ...
  
  @mock.patch('fire.interact.Embed')
  def testInteractiveModeVariables(self, mock_embed):
    ...
  
  @mock.patch('fire.interact.Embed')
  def testInteractiveModeVariablesWithName(self, mock_embed):
    ...
  
  def testHelpWithClass(self):
    ...
  
  def testHelpWithMember(self):
    ...
  
  def testHelpOnErrorInConstructor(self):
    ...
  
  def testHelpWithNamespaceCollision(self):
    ...
  
  def testInvalidParameterRaisesFireExit(self):
    ...
  
  def testErrorRaising(self):
    ...
  
  def testFireError(self):
    ...
  
  def testFireErrorMultipleValues(self):
    ...
  
  def testPrintEmptyDict(self):
    ...
  
  def testPrintOrderedDict(self):
    ...
  
  def testPrintNamedTupleField(self):
    ...
  
  def testPrintNamedTupleFieldNameEqualsValue(self):
    ...
  
  def testPrintNamedTupleIndex(self):
    ...
  
  def testPrintSet(self):
    ...
  
  def testPrintFrozenSet(self):
    ...
  
  def testPrintNamedTupleNegativeIndex(self):
    ...
  
  def testCallable(self):
    ...
  
  def testCallableWithPositionalArgs(self):
    ...
  
  def testStaticMethod(self):
    ...
  
  def testClassMethod(self):
    ...
  
  @testutils.skipIf(six.PY2, 'lru_cache is Python 3 only.')
  def testLruCacheDecoratorBoundArg(self):
    ...
  
  @testutils.skipIf(six.PY2, 'lru_cache is Python 3 only.')
  def testLruCacheDecorator(self):
    ...
  


if __name__ == '__main__':
  ...
