"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for custom description module."""
LINE_LENGTH = 80
class CustomDescriptionTest(testutils.BaseTestCase):
  def test_string_type_summary_enough_space(self):
    ...
  
  def test_string_type_summary_not_enough_space_truncated(self):
    ...
  
  def test_string_type_summary_not_enough_space_new_line(self):
    ...
  
  def test_string_type_summary_not_enough_space_long_truncated(self):
    ...
  
  def test_string_type_description_enough_space(self):
    ...
  
  def test_string_type_description_not_enough_space_truncated(self):
    ...
  
  def test_string_type_description_not_enough_space_new_line(self):
    ...
  


if __name__ == '__main__':
  ...
