"""
This type stub file was generated by pyright.
"""

from fire import docstrings, testutils

"""Tests for fire docstrings module."""
DocstringInfo = docstrings.DocstringInfo
ArgInfo = docstrings.ArgInfo
class DocstringsTest(testutils.BaseTestCase):
  def test_one_line_simple(self):
    ...
  
  def test_one_line_simple_whitespace(self):
    ...
  
  def test_one_line_too_long(self):
    ...
  
  def test_one_line_runs_over(self):
    ...
  
  def test_one_line_runs_over_whitespace(self):
    ...
  
  def test_google_format_args_only(self):
    ...
  
  def test_google_format_arg_named_args(self):
    ...
  
  def test_google_format_typed_args_and_returns(self):
    ...
  
  def test_rst_format_typed_args_and_returns(self):
    ...
  
  def test_numpy_format_typed_args_and_returns(self):
    ...
  
  def test_multisection_docstring(self):
    ...
  
  def test_google_section_with_blank_first_line(self):
    ...
  
  def test_ill_formed_docstring(self):
    ...
  
  def test_strip_blank_lines(self):
    ...
  
  def test_numpy_colon_in_description(self):
    ...
  


if __name__ == '__main__':
  ...
