"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests importing the fire module."""
class FireImportTest(testutils.BaseTestCase):
  """Tests importing Fire."""
  def testFire(self):
    ...
  
  def testFireMethods(self):
    ...
  
  def testNoPrivateMethods(self):
    ...
  


if __name__ == '__main__':
  ...
