"""
This type stub file was generated by pyright.
"""

import platform
import sys

"""This module is used for enabling formatting on Windows."""
def initialize_or_disable():
  """Enables ANSI processing on Windows or disables it as needed."""
  ...

if sys.platform.startswith('win'):
  ...
