"""
This type stub file was generated by pyright.
"""

import mock
from fire import testutils

"""Tests for the interact module."""
class InteractTest(testutils.BaseTestCase):
  @mock.patch(INTERACT_METHOD)
  def testInteract(self, mock_interact_method):
    ...
  
  @mock.patch(INTERACT_METHOD)
  def testInteractVariables(self, mock_interact_method):
    ...
  


if __name__ == '__main__':
  ...
