"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Test using Fire via `python -m fire`."""
class MainModuleTest(testutils.BaseTestCase):
  """Tests to verify the behavior of __main__ (python -m fire)."""
  def testNameSetting(self):
    ...
  
  def testArgPassing(self):
    ...
  


if __name__ == '__main__':
  ...
