"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the parser module."""
class ParserTest(testutils.BaseTestCase):
  def testCreateParser(self):
    ...
  
  def testSeparateFlagArgs(self):
    ...
  
  def testDefaultParseValueStrings(self):
    ...
  
  def testDefaultParseValueQuotedStrings(self):
    ...
  
  def testDefaultParseValueSpecialStrings(self):
    ...
  
  def testDefaultParseValueNumbers(self):
    ...
  
  def testDefaultParseValueStringNumbers(self):
    ...
  
  def testDefaultParseValueQuotedStringNumbers(self):
    ...
  
  def testDefaultParseValueOtherNumbers(self):
    ...
  
  def testDefaultParseValueLists(self):
    ...
  
  def testDefaultParseValueBareWordsLists(self):
    ...
  
  def testDefaultParseValueDict(self):
    ...
  
  def testDefaultParseValueNone(self):
    ...
  
  def testDefaultParseValueBool(self):
    ...
  
  def testDefaultParseValueBareWordsTuple(self):
    ...
  
  def testDefaultParseValueNestedContainers(self):
    ...
  
  def testDefaultParseValueComments(self):
    ...
  
  def testDefaultParseValueBadLiteral(self):
    ...
  
  def testDefaultParseValueSyntaxError(self):
    ...
  
  def testDefaultParseValueIgnoreBinOp(self):
    ...
  


if __name__ == '__main__':
  ...
