"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Test the test utilities for Fire's tests."""
class TestTestUtils(testutils.BaseTestCase):
  """Let's get meta."""
  def testNoCheckOnException(self):
    ...
  
  def testCheckStdoutOrStderrNone(self):
    ...
  
  def testCorrectOrderingOfAssertRaises(self):
    ...
  


if __name__ == '__main__':
  ...
