"""
This type stub file was generated by pyright.
"""

"""Python Fire test components Fire CLI.

This file is useful for replicating test results manually.
"""
def main():
  ...

if __name__ == '__main__':
  ...
