"""
This type stub file was generated by pyright.
"""

from fire import testutils

"""Tests for the trace module."""
class FireTraceTest(testutils.BaseTestCase):
  def testFireTraceInitialization(self):
    ...
  
  def testFireTraceGetResult(self):
    ...
  
  def testFireTraceHasError(self):
    ...
  
  def testAddAccessedProperty(self):
    ...
  
  def testAddCalledCallable(self):
    ...
  
  def testAddCalledRoutine(self):
    ...
  
  def testAddInstantiatedClass(self):
    ...
  
  def testAddCompletionScript(self):
    ...
  
  def testAddInteractiveMode(self):
    ...
  
  def testGetCommand(self):
    ...
  
  def testGetCommandWithQuotes(self):
    ...
  
  def testGetCommandWithFlagQuotes(self):
    ...
  


class FireTraceElementTest(testutils.BaseTestCase):
  def testFireTraceElementHasError(self):
    ...
  
  def testFireTraceElementAsStringNoMetadata(self):
    ...
  
  def testFireTraceElementAsStringWithTarget(self):
    ...
  
  def testFireTraceElementAsStringWithTargetAndLineNo(self):
    ...
  


if __name__ == '__main__':
  ...
