"""
This type stub file was generated by pyright.
"""

def makeStyles(chalkInst, styleInputList):
    ...

def makeOrderedStyles(*, chalkInst, styleListStartCodePairs, styleType):
    ...

def makePrefixedOrderedStyles(*, chalkInst, prefix, styleListStartCodePairs, styleType):
    ...

