"""
This type stub file was generated by pyright.
"""

class Style:
    def __init__(self, name, code, styleType) -> None:
        ...
    
    def __get__(self, instance, _owner):
        ...
    
    def __set__(self, instance, value):
        ...
    


