"""
This type stub file was generated by pyright.
"""

moduleName = "appendAll"
def appendAll(collectionToAppend):
    ...

def appendAll_list(listToAppend, aList):
    ...

_typeToAppendAll = { list: appendAll_list }
