"""
This type stub file was generated by pyright.
"""

moduleName = "keepWhen"
def keepWhen(predicate):
    ...

def keepWhen_list(shouldKeep, aList):
    ...

def keepWhen_dict(shouldKeep, aDict):
    ...

_typeToKeepWhen = { list: keepWhen_list,dict: keepWhen_dict }
