"""
This type stub file was generated by pyright.
"""

from inspect import Parameter

_nonVarPositionalParamKinds = Parameter.POSITIONAL_ONLY, Parameter.POSITIONAL_OR_KEYWORD
def getNumPositionalParams(fn, callerName):
    ...

