"""
This type stub file was generated by pyright.
"""

from google.cloud import _http

"""
This type stub file was generated by pyright.
"""
class Connection(_http.JSONConnection):
    """A connection to Google Cloud Storage via the JSON REST API.

    :type client: :class:`~google.cloud.storage.client.Client`
    :param client: The client that owns the current connection.

    :type client_info: :class:`~google.api_core.client_info.ClientInfo`
    :param client_info: (Optional) instance used to generate user agent.
    """
    DEFAULT_API_ENDPOINT = ...
    def __init__(self, client, client_info=..., api_endpoint=...) -> None:
        ...
    
    API_VERSION = ...
    API_URL_TEMPLATE = ...
    def api_request(self, *args, **kwargs):
        ...
    


