"""
This type stub file was generated by pyright.
"""

import simple_chalk.src.utils as _
from .src.makeAChalkInstance import makeAChalkInstance as newChalk

chalk = newChalk()
def doesntStartWith(prefix):
    ...

chalkClass = type(chalk)
def setGlobal(attrName):
    ...

